services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 8080:80
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    environment:
      PORT: 3000
      NODE_ENV: production
    ports:
      - 3000:3000
    restart: unless-stopped